# Generated by Django 5.1.3 on 2024-12-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="song",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
