# Generated by Django 5.1.3 on 2024-12-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_song_album_song_spotify_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="songs.genre"
            ),
        ),
        migrations.CreateModel(
            name="UserMusicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_songs_downloaded", models.PositiveIntegerField(default=0)),
                (
                    "last_recommendation_generated",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "favorite_genres",
                    models.ManyToManyField(blank=True, to="songs.genre"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
