# Generated by Django 5.0.2 on 2025-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_genre_song_genres_usermusicprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="songs/images/"),
        ),
    ]
