# Generated by Django 5.0.2 on 2025-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0005_song_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
