# Generated by Django 5.0.2 on 2025-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0006_alter_song_file_alter_song_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="image",
        ),
        migrations.AddField(
            model_name="song",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(upload_to="songs/"),
        ),
    ]
