# Generated by Django 5.0.2 on 2025-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0007_remove_song_image_song_thumbnail_url_alter_song_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="song_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
