# Generated by Django 5.1.3 on 2025-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0008_song_song_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("current_progress", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                ("current_file", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "estimated_completion_time",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
