# Generated by Django 5.1.3 on 2025-03-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0009_downloadprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(
                blank=True, related_name="playlists", to="songs.song"
            ),
        ),
    ]
